name: db_indexeddb
version: 0.0.1
resolution: workspace
environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  plugin:
    platforms:
      web:
        pluginClass: DbIndexeddbWeb
        fileName: db_indexeddb_web.dart