name: CI

on:
  push:
    branches: [ 'main' ]
    paths:
      - '.github/workflows/verify.yml'
      - 'assets/**'
      - 'lib/**'
      - 'test/**'
      - 'web/**'
      - 'analysis_options.yaml'
      - 'pubspec.*'

jobs:

  verify:
    uses: ./.github/workflows/verify.yml

  deploy:
    needs: verify
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/deploy.yml
    with:
      cloudflare_env: dev
      dev_build: true
    secrets: inherit
