name: Stage

concurrency: stage

on:
  workflow_dispatch:

jobs:

  verify:
    uses: ./.github/workflows/verify.yml

  tag:
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      contents: write
    steps:
      - if: github.ref != 'refs/heads/main'
        run: exit 1
      - uses: actions/checkout@v4
      - id: version
        run: |
          HASH="$(git rev-parse --short HEAD)"
          DATE="$(git show -s --format=%ci $HASH | cut -c1-10)"
          VERSION="v$DATE.$HASH"
          echo "tag_name=$VERSION" >> "$GITHUB_OUTPUT"
      - name: tag
        id: tag
        env:
          TAG_NAME: ${{ steps.version.outputs.tag_name }}
        run: |
          git config --global user.name "Adam McKee"
          git config --global user.email "adam.be.g84d@gmail.com"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
    outputs:
      tag_name: ${{ steps.version.outputs.tag_name }}

  release:
    needs: tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: www.zip
      - env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ needs.tag.outputs.tag_name }}
        run: |
          gh release create "$TAG_NAME" \
            --prerelease=false \
            --latest=true \
            --notes "https://www.youtube.com/watch?v=GNEzg5pRJzA" \
            --repo eighty4/picking_playmate \
            www.zip

  deploy:
    needs: [ release, tag ]
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/deploy.yml
    with:
      cloudflare_env: stage
      release_version: ${{ needs.tag.outputs.tag_name }}
    secrets: inherit
