name: Verify

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/verify.yml
      - assets/**
      - lib/**
      - test/**
      - web/**
      - analysis_options.yaml
      - pubspec.*
  pull_request:
    branches: [ main ]

env:
  flutter_version: 3.27.1

jobs:

  verify:
    runs-on: ubuntu-latest
    needs:
      - analyze
      - format
      - test
    steps:
      - run: echo ""

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pp
      - uses: actions/checkout@v4
        with:
          repository: eighty4/libtab
          path: libtab
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
      - name: analyze
        run: flutter analyze
        working-directory: pp

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pp
      - uses: actions/checkout@v4
        with:
          repository: eighty4/libtab
          path: libtab
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
      - name: format
        run: dart format lib test --set-exit-if-changed
        working-directory: pp

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pp
      - uses: actions/checkout@v4
        with:
          repository: eighty4/libtab
          path: libtab
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
      - name: test
        run: flutter test
        working-directory: pp

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pp
      - uses: actions/checkout@v4
        with:
          repository: eighty4/libtab
          path: libtab
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
      - name: build web
        run: flutter build web
        working-directory: pp
