name: Verify
run-name: "Verify ${{ github.sha }} (${{ github.ref_name }})"

on:
  pull_request:
    branches: ["*"]
  workflow_call:

env:
  flutter_version: 3.32.2

jobs:
  verify:
    runs-on: ubuntu-latest
    needs:
      - analyze
      - build
      - format
      - test
    steps:
      - run: echo "And up through the ground come a green passing build"

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pp
      - uses: actions/checkout@v4
        with:
          repository: eighty4/libtab
          path: libtab
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: "stable"
      - name: analyze
        run: flutter analyze
        working-directory: pp

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pp
      - uses: actions/checkout@v4
        with:
          repository: eighty4/libtab
          path: libtab
      - uses: flutter-actions/setup-flutter@v4
        with:
          cache-sdk: true
          version: ${{ env.flutter_version }}
      - name: build web
        run: flutter build web
        working-directory: pp
      - run: (cd pp/build/web && zip -qr ../../../www.zip .)
      - uses: actions/upload-artifact@v4
        with:
          name: www.zip
          path: www.zip
          if-no-files-found: error

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pp
      - uses: actions/checkout@v4
        with:
          repository: eighty4/libtab
          path: libtab
      - uses: flutter-actions/setup-flutter@v4
        with:
          cache-sdk: true
          version: ${{ env.flutter_version }}
      - name: format
        run: dart format lib test --set-exit-if-changed
        working-directory: pp

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pp
      - uses: actions/checkout@v4
        with:
          repository: eighty4/libtab
          path: libtab
      - uses: flutter-actions/setup-flutter@v4
        with:
          cache-sdk: true
          version: ${{ env.flutter_version }}
      - name: test
        run: flutter test
        working-directory: pp
